version: '3.9'

# Note - changing username / password / db might require you to delete old images / containers first
services:
  postgres-db:
    image: 'postgres:14-alpine'
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-user -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      # TODO: Figure out how to keep consistent with application.properties and Dockerfile
      - "8000:8000"
    container_name: app
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres-user
      - SPRING_DATASOURCE_PASSWORD=postgres-password