version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      # TODO: Figure out how to keep consistent with application.properties and Dockerfile
      - "8000:8000"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres

  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres