name: Deploy staging branch to staging env

on:
  push:
    branches: [ staging ]

env:
  TF_WORKSPACE_NAME: staging
  TF_WORKING_DIR: infra
  SERVICE_NAME: consulting-performance-mgmt-staging
  SERVICE_PORT: 8080

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # TODO: Check out keyless authentication for service accounts
      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: Terraform select workspace
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform workspace select $TF_WORKSPACE_NAME
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}
          TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_db_username_secret: ${{ vars.DB_USERNAME_SECRET }}
          TF_VAR_db_username_secret_version: ${{ vars.DB_USERNAME_SECRET_VERSION }}
          TF_VAR_db_password_secret: ${{ vars.DB_PASSWORD_SECRET }}
          TF_VAR_db_password_secret_version: ${{ vars.DB_PASSWORD_SECRET_VERSION }}
          TF_VAR_region: ${{ vars.REGION }}

#      - name: Fetch required Terraform outputs
#        working-directory: ${{ env.TF_WORKING_DIR }}
  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_CREDENTIALS }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      # TODO: Find a way to delete all images in repo first
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            SERVER_PORT=${{ env.SERVICE_PORT }}
          tags: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          push: false

      - name: Push Docker image to artifact registry
        run: docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/$SERVICE_NAME:${{ github.sha }}

#        - name: Deploy
#          uses: google-github-actions/deploy-cloudrun@v1.0.1
#          with:
#            service: ${{ env.SERVICE_NAME }}
#            image: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
#            env_vars: |
#              PORT=$SERVICE_PORT
#              SPRING_PROFILE=staging
#              DB_CONNECTION_NAME=${{ vars.GCP_PROJECT_ID }}:${{ vars.REGION }}:
#              GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}
#              DB_USERNAME_SECRET=${{ vars.DB_USERNAME_SECRET }}
#              DB_USERNAME_SECRET_VERSION=${{ vars.DB_USERNAME_SECRET_VERSION }}
#              DB_PASSWORD_SECRET=${{ vars.DB_PASSWORD_SECRET }}
#              DB_PASSWORD_SECRET_VERSION=${{ vars.DB_PASSWORD_SECRET_VERSION }}